variables:
  DOCKER_DRIVER: overlay

image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build-master:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

deploy-master:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment veneza --stack producao --service web
  only:
    - master
  when: manual

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment veneza --stack $CI_COMMIT_REF_SLUG --service web
  when: manual
