language: python

python:
  - "2.7"

cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - libxml2-dev
      - libxmlsec1-dev
      - libxslt-dev
      - gcc 
      - python2.7-dev
      - libevent-dev
      - libsasl2-dev
      - libldap2-dev
      - libpq-dev
      - libpng12-dev
      - libjpeg-dev

env:
  - VERSION="10.0" ODOO_REPO="odoo/odoo"
  - VERSION="10.0" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - sudo locale-gen en_US en_US.UTF-8 pt_BR.UTF-8
  - sudo dpkg-reconfigure locales
  - virtualenv .
  - bin/pip install -U pip zc.buildout
  - echo "[buildout] 
  extends = 
https://raw.githubusercontent.com/odoo-brazil/odoo-brazil-buildout/10.0/default.cfg"

script:
  - bin/buildout

