version: '2'
volumes:
  PostgresV:
    external: true
    driver: nfs
  OdooV:
    external: true
    driver: nfs
services:
  web:  
    image: gitlab.kmee.com.br:5043/odoo/produto:develop
    stdin_open: true
    volumes:
    - PostgresV:/var/run/postgresql
    - OdooV:/opt/odoo/.local/share/Odoo
    tty: true
    links:
    - db:postgres
    labels:
      io.rancher.container.pull_image: always
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    volumes:
    - PostgresV:/var/run/postgresql
  auth-lb:
    image: rancher/lb-service-haproxy:v0.7.6
    ports:
    - 6574:9000/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'