version: '2'
volumes:
  postgres_volume_config:
    driver: rancher-nfs
    external: true
  postgres_volume_log:
    driver: rancher-nfs
    external: true
  postgres_volume_data:
    driver: rancher-nfs
    external: true
  odoo_files:
    driver: rancher-nfs
    external: true
services:
  web:  
    image: gitlab.kmee.com.br:5043/odoo/produto:develop
    stdin_open: true
    volumes:
    - odoo_files:/opt/odoo/.local/share/Odoo
    tty: true
    links:
    - db:postgres
    labels:
      io.rancher.container.pull_image: always
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    volumes:
    - postgres_volume_config:/etc/postgresql-common/
    - postgres_volume_log:/var/log/postgresql/
    - postgres_volume_data:/var/lib/postgresql/data/
  auth-lb:
    image: rancher/lb-service-haproxy:v0.7.6
    ports:
    - 9001:9001/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
